# Generated by Django 5.1.2 on 2024-11-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTT',
            fields=[
                ('CTT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Case_Description', models.CharField(max_length=255)),
                ('IMSI', models.BigIntegerField()),
                ('MSISDN', models.BigIntegerField()),
                ('CTT_Created_Date', models.DateTimeField()),
            ],
            options={
                'db_table': 'case_tt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MSISDNIMSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSISDN', models.BigIntegerField()),
                ('IMSI', models.BigIntegerField()),
            ],
            options={
                'db_table': 'msisdn_imsi',
                'managed': False,
            },
        ),
    ]
