### Login to get JWT token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}


### Call API
GET http://127.0.0.1:8000/api/transfer/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMTI2Nzk2LCJpYXQiOjE3MzMxMjY0OTYsImp0aSI6IjU5NzFiNzdlODc1YjQzMDQ5YTUwNzY2YjcyMGU1ZmY5IiwidXNlcl9pZCI6MX0.9twnnKlNroNBRviWyYKkH4JenKeVgdkpFAeM9MeqS0c